sudo: required

language: java

services:
  - docker

install:
  - docker run -d --name tomcat tomcat
  - docker run --name some-postgres -e POSTGRES_HOST=localhost -e POSTGRES_PORT=5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=kurs_aggr -d postgres:9.3
  - mvn package
  - cp target/component-aggregator-1.0.0-SNAPSHOT.jar src/main/docker
  - docker build -t my_app_component_aggregator src/main/docker

script:
  - docker run --link tomcat:tomcat --link some-postgres:postgres my_app_component_aggregator /bin/sh
