sudo: required

language: java

services:
  - docker

install:
  - docker run -d --name tomcat tomcat
  - docker run --name some-postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=kurs_aggr -d postgres
  - docker build -t my_app_component_aggregator src/main/docker

script:
  - docker run --link tomcat:tomcat --link some-postgres:postgres my_app_component_aggregator /bin/sh 
